# .github/workflows/deploy.yml
name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read      # for checkout
  pages: write        # to create/update GitHub Pages
  id-token: write     # required by configure-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo (with GITHUB_TOKEN persisted)
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. Setup Node.js (v20 for built-in webcrypto)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install dependencies and build into docs/
      - name: Install & Build
        run: |
          npm ci
          npm run build

      # 4. Configure GitHub Pages (create site if needed)
      - name: Configure Pages
        uses: actions/configure-pages@v2
        with:
          github-token: ${{ secrets.PAGES_PAT }}

      # 5. Upload the docs/ folder as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      # 6. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github-token: ${{ secrets.PAGES_PAT }}